version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chamados_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  redis:
    image: redis:alpine
    container_name: chamados_redis
    networks:
      - backend-net

  backend:
    build: ./backend
    container_name: chamados_backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - db
      - redis
    networks:
      - frontend-net
      - backend-net

  worker:
    build: ./worker
    container_name: chamados_worker
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - backend-net

  frontend:
    build: ./frontend
    container_name: chamados_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - frontend-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  db_data:
  grafana_data: